from __future__ import annotations

import json
from pathlib import Path

from scripts.validate.checks.common import Finding, read_text
from scripts.validate.checks.feature_memory import feature_memory_roots

def validate_qa_evidence(root: Path) -> list[Finding]:
    findings: list[Finding] = []
    required_commands = [
        "validate-tools project-layout .",
    ]
    if (root / "docker-compose.yml").exists():
        required_commands.append("docker compose up")
        if (root / "frontend").exists():
            required_commands.append("runtime-smoke.py")
    for memory_root in feature_memory_roots(root):
        for slice_md in memory_root.rglob("slice.md"):
            if "history" in slice_md.relative_to(memory_root).parts:
                continue
            text = read_text(slice_md)
            is_minimal = "template-minimal" in text or "Minimal Slice" in text
            if is_minimal:
                continue
            slice_dir = slice_md.parent
            evidence_json = slice_dir / "qa-evidence.json"
            rel = slice_dir.relative_to(root).as_posix()
            if (root / "docker-compose.yml").exists() and (root / "frontend").exists() and not (slice_dir / "runtime-smoke.json").exists():
                findings.append(Finding(f"{rel}/runtime-smoke.json", "full frontend slice must define runtime smoke URL and rendered-content assertions"))
            if not evidence_json.exists():
                findings.append(Finding(f"{rel}/qa-evidence.json", "full slice must record deterministic QA evidence JSON"))
                continue
            try:
                data = json.loads(read_text(evidence_json))
            except json.JSONDecodeError as exc:
                findings.append(Finding(evidence_json.relative_to(root).as_posix(), f"invalid QA evidence JSON: {exc}"))
                continue
            runs = data.get("runs") if isinstance(data, dict) else None
            generated_by = data.get("generated_by") if isinstance(data, dict) else None
            if not isinstance(generated_by, dict):
                findings.append(Finding(evidence_json.relative_to(root).as_posix(), "QA evidence must include generated_by metadata for gate.py"))
            else:
                gate_command = str(generated_by.get("command", "")).replace("/", "\\")
                if "scripts\\validate\\gate.py" not in gate_command:
                    findings.append(Finding(evidence_json.relative_to(root).as_posix(), "QA evidence must be generated by scripts\\validate\\gate.py"))
            if not isinstance(runs, list) or not runs:
                findings.append(Finding(evidence_json.relative_to(root).as_posix(), "QA evidence JSON must contain non-empty runs[]"))
                continue
            for index, run in enumerate(runs, start=1):
                if not isinstance(run, dict):
                    findings.append(Finding(evidence_json.relative_to(root).as_posix(), f"QA evidence run {index} must be an object"))
                    continue
                for key in ["command", "cwd", "exit_code", "started_at", "finished_at", "output_path"]:
                    if key not in run:
                        findings.append(Finding(evidence_json.relative_to(root).as_posix(), f"QA evidence run {index} missing {key}"))
                if run.get("exit_code") != 0:
                    findings.append(Finding(evidence_json.relative_to(root).as_posix(), f"QA evidence run {index} did not pass"))
            evidence_text = json.dumps(data)
            command_text = "\n".join(
                str(run.get("command", "")).replace("/", "\\")
                for run in runs
                if isinstance(run, dict)
            )
            for command in required_commands:
                if command not in command_text:
                    findings.append(Finding(rel, f"QA evidence missing command: {command}"))
            if (root / "backend").exists():
                backend_runs = [
                    run
                    for run in runs
                    if isinstance(run, dict)
                    and str(run.get("cwd", "")).replace("/", "\\") == "backend"
                    and "--cov=src" in str(run.get("command", ""))
                ]
                if not backend_runs:
                    findings.append(Finding(rel, "QA evidence missing backend test command running from ./backend"))
            if (root / "frontend").exists():
                frontend_commands = {
                    "frontend test": "--dir frontend test:coverage",
                    "frontend build": "--dir frontend build",
                    "frontend e2e": "--dir frontend e2e",
                }
                for label, command in frontend_commands.items():
                    if command not in command_text:
                        findings.append(Finding(rel, f"QA evidence missing {label} command"))
            coverage_entries = data.get("unit_coverage") if isinstance(data, dict) else None
            if not isinstance(coverage_entries, list) or not coverage_entries:
                findings.append(Finding(evidence_json.relative_to(root).as_posix(), "QA evidence must include unit_coverage[]"))
            else:
                seen_surfaces: set[str] = set()
                for index, entry in enumerate(coverage_entries, start=1):
                    if not isinstance(entry, dict):
                        findings.append(Finding(evidence_json.relative_to(root).as_posix(), f"unit_coverage entry {index} must be an object"))
                        continue
                    surface = str(entry.get("surface", ""))
                    seen_surfaces.add(surface)
                    minimum = entry.get("minimum_percent", data.get("coverage_threshold", 80))
                    actual = entry.get("actual_percent")
                    if not isinstance(minimum, (int, float)) or minimum < 80:
                        findings.append(Finding(evidence_json.relative_to(root).as_posix(), f"unit_coverage entry {index} must require at least 80 percent"))
                    if not isinstance(actual, (int, float)):
                        findings.append(Finding(evidence_json.relative_to(root).as_posix(), f"unit_coverage entry {index} missing actual_percent"))
                    elif isinstance(minimum, (int, float)) and actual < minimum:
                        findings.append(Finding(evidence_json.relative_to(root).as_posix(), f"{surface or 'unit'} coverage {actual}% is below required {minimum}%"))
                    if not entry.get("summary_path"):
                        findings.append(Finding(evidence_json.relative_to(root).as_posix(), f"unit_coverage entry {index} missing summary_path"))
                if (root / "backend").exists() and "backend" not in seen_surfaces:
                    findings.append(Finding(evidence_json.relative_to(root).as_posix(), "QA evidence missing backend unit coverage"))
                if (root / "frontend").exists() and "frontend" not in seen_surfaces:
                    findings.append(Finding(evidence_json.relative_to(root).as_posix(), "QA evidence missing frontend unit coverage"))
            e2e_coverage_path = data.get("e2e_coverage_path") if isinstance(data, dict) else None
            if not isinstance(e2e_coverage_path, str) or not e2e_coverage_path:
                findings.append(Finding(evidence_json.relative_to(root).as_posix(), "QA evidence missing e2e_coverage_path"))
            elif not (root / e2e_coverage_path).exists():
                findings.append(Finding(e2e_coverage_path, "QA evidence points to missing E2E coverage JSON"))
    return findings
def validate_tooling(root: Path) -> list[Finding]:
    findings: list[Finding] = []
    for rel in [".codex/hooks/verify-subagent.sh", ".claude/hooks/verify-subagent.sh"]:
        path = root / rel
        if not path.exists():
            continue
        text = read_text(path)
        if "validate-tools run" in text and "project-layout" not in text:
            findings.append(Finding(rel, "validate-tools run requires config; use concrete validate-tools commands or generated JSON"))
        if "pyproject.toml" in text and "backend/pyproject.toml" not in text:
            findings.append(Finding(rel, "backend checks must inspect backend/pyproject.toml, not only root pyproject.toml"))
        if "package.json" in text and "frontend/package.json" not in text:
            findings.append(Finding(rel, "frontend checks must inspect frontend/package.json, not only root package.json"))
    package_json = root / "frontend/package.json"
    if package_json.exists():
        try:
            package = json.loads(read_text(package_json))
        except json.JSONDecodeError as exc:
            findings.append(Finding("frontend/package.json", f"invalid JSON: {exc}"))
            return findings
        lint = package.get("scripts", {}).get("lint", "")
        if lint == "next lint":
            findings.append(Finding("frontend/package.json", "lint script must be non-interactive; next lint may prompt without config"))
    return findings

